name: 'marvin_entity_resolution'
version: '1.0.0'

config-version: 2
profile: 'duckdb-marvin'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets: 
  - "target"
  - "dbt_modules"

models:
  marvin_entity_resolution:
    foundation:
      +materialized: table
